sudo: required
dist: trusty
language: csharp
mono: none
dotnet: 1.0.1
services:
  - docker

script:
  - dotnet restore ./AuthServer.sln 
  - dotnet test ./AuthServer.Tests/AuthServer.Tests.csproj
  - dotnet publish ./AuthServer.sln -c Release -o ./obj/Docker/publish
  - docker build ./AuthServer.Host/ -t $DOCKER_USERNAME/authserver:latest;

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/authserver;
    fi
