language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
script:
  - dotnet restore ./AuthServer.sln 
  - dotnet test ./AuthServer.Tests/AuthServer.Tests.csproj
  - dotnet publish ./AuthServer.sln